export default {
  appState: "",
  apiAlarmServiceCallsInProgress: 0,
  alarms: [],
  channelsDataToSystem: [],
  isInitilizedModelsStructureJson: "false",
  isInitializeStructureAllObjectWithBasicInfoJson: "false",
  isInitializeStructureAllObjectToFastModifyJson: "false",
  isConnectedWebSocketModelsStructureJsonActions: false,
  messagesWebSocketModelsStructureJsonActions: [],
  structureAllObjectWithBasicInfoJson: [],
  structureAllObjectToFastModifyJson: "",
  mstrs: [],
  apiMstrsServiceCallsInProgress: 0,
  loggedUser: "guest",
};
